version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/generators/ionic/resources/base'
    schedule:
      interval: 'weekly'
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "zone.js"
          - "@angular-devkit/*"
          - "@angular-builders/*"
      angular-eslint:
        patterns:
          - "@angular-eslint/*"
      capacitor:
        patterns:
          - '@capacitor/*'
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
