version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/generators/ionic/resources/base'
    schedule:
      interval: 'weekly'
    groups:
      angular:
        patterns:
          - "@angular/*"
      angular-eslint:
        patterns:
          - "@angular-eslint/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
