version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/generators/ionic/resources/base'
    schedule:
      interval: 'weekly'
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@fortawesome/angular-fontawesome'
          - 'ngx-webstorage'
          - 'typescript'
          - 'zone.js'
          - '@angular-builders/jest'
          - 'jest'
          - 'jest-preset-angular'
          - '@types/jest'
      angular-eslint:
        patterns:
          - '@angular-eslint/*'
      capacitor:
        patterns:
          - '@capacitor/*'
          - 'capacitor-secure-storage-plugin'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
