os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "9.5.0"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=1
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
    - APP_FOLDER=$HOME/backend
    - IONIC_FOLDER=$HOME/ionic4j
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
  matrix:
    - JHIPSTER=ngx-mysql PROFILE=dev PROTRACTOR=1
    - JHIPSTER=ngx-oauth2 PROFILE=dev PROTRACTOR=1
before_install:
  - export TZ=America/Denver
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm -g install yo ionic
  - chmod +x $JHIPSTER_INSTALL/*.sh
  - chmod +x $JHIPSTER_SCRIPTS/*.sh
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$TRAVIS_PULL_REQUEST, BRANCH=$BRANCH"
install:
  - $JHIPSTER_INSTALL/01-install-jhipster-stack.sh
  - $JHIPSTER_INSTALL/02-checkVersion.sh
script:
  - $JHIPSTER_SCRIPTS/01-generate-entities.sh
  - $JHIPSTER_SCRIPTS/02-generate-project.sh
  - $JHIPSTER_SCRIPTS/03-docker-compose.sh
  - $JHIPSTER_SCRIPTS/04-tests.sh
  - $JHIPSTER_SCRIPTS/05-run.sh
